version: "2"
linters:
  enable:
    - errorlint
    - forbidigo
    - gocritic
    - godot
    - lll
    - reassign
    - revive
    - staticcheck
    - testpackage
    - unconvert
  settings:
    lll:
      line-length: 100
      tab-width: 4
  exclusions:
    presets:
      - std-error-handling
    rules:
      - linters:
          - lll
        source: "\t?// *(see )?https://"
formatters:
  enable:
    - goimports
