//go:build !openssl

// tarantoolee_gost_pure_integration_test.go — GOST cipher suite interop with
// a locally installed Tarantool Enterprise Edition binary, using the pure-Go
// GOST TLS stack (no cgo, no gost-engine dylib).
//
// Run:
//
//	go test -v -count=1 -run TestTarantoolEE_Ping_GOST_Pure ./integration/
//
// The test skips (not fails) when any of the following are absent:
//   - Tarantool EE binary
//   - testdata/tarantool/certs/{ca.crt,server_gost.crt,...} — generated by
//     testdata/tarantool/certs/gen.sh when a gost-engine is present; the GOST
//     pair may be absent on machines without gost-engine.
//
// Unlike the cgo path (TestTarantoolEE_Ping_GOST), this test does NOT check
// for gost-engine.cnf or gost.dylib — the pure-Go stack does not load them.
// Tarantool's subprocess environment still has OPENSSL_CONF stripped (handled
// by startTarantool) because Tarantool EE uses its own statically-compiled
// OpenSSL (with built-in GOST support) and a host OPENSSL_CONF that loads an
// external engine can cause NID conflicts.

package integration_test

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	tlsdialer "github.com/tarantool/go-tlsdialer/v2"
	"github.com/tarantool/go-tlsdialer/v2/backend/gostls"
)

// gostPingCiphersPure is the set of GOST cipher suites exercised by
// TestTarantoolEE_Ping_GOST_Pure.
//
// Only the two suites that the pure-Go registry actually registers
// (tls/internal/suites/gost_suites.go) are listed:
//
//   - 0x0081 (GOST2001-GOST89-GOST89) — VKO 2001 + 28147 CNT + IMIT + GOST R 34.11-94 PRF.
//   - 0xFF85 (GOST2012-GOST8912-GOST8912) — VKO 2012 + 28147 CNT + IMIT + Streebog-256 PRF.
//
// No "LEGACY-" prefix (that's a gost-engine-side alias, not a pure-Go name).
//
// The KUZNYECHIK / MAGMA suites (RFC 9367) use the GOST 2018 key transport
// (Kx=GOST18) implemented in tls/internal/ke/gost2018.go.
var gostPingCiphersPure = []string{
	"GOST2001-GOST89-GOST89",
	"GOST2012-GOST8912-GOST8912",
	"GOST2012-KUZNYECHIK-KUZNYECHIKOMAC",
	"GOST2012-MAGMA-MAGMAOMAC",
}

// TestTarantoolEE_Ping_GOST_Pure launches a Tarantool EE instance configured
// with the appropriate GOST server cert and exercises a Ping over each
// pure-Go GOST cipher suite.
//
// This test is the pure-Go counterpart of TestTarantoolEE_Ping_GOST, which
// takes the cgo path and therefore stays behind the openssl build tag.
// Structural shape is kept deliberately identical to ease future maintenance.
func TestTarantoolEE_Ping_GOST_Pure(t *testing.T) {
	skipUnlessTarantoolEE(t)

	certs, ok := certPaths(t)
	if !ok {
		t.Skip("testdata/tarantool/certs not populated; run testdata/tarantool/certs/gen.sh")
	}

	for _, cipher := range gostPingCiphersPure {
		cipher := cipher
		t.Run(cipher, func(t *testing.T) {
			t.Parallel()

			// Use a short /tmp/ttee-* workdir to stay under the macOS Unix
			// socket path limit (~104 bytes) that t.TempDir() busts.
			workDir, err := os.MkdirTemp("/tmp", "ttee-")
			require.NoError(t, err, "mkdtemp")
			t.Cleanup(func() { _ = os.RemoveAll(workDir) })

			port := reservePort(t)
			cfgPath := filepath.Join(workDir, "config.yml")

			cfg, err := os.Create(cfgPath)
			require.NoError(t, err, "create config")
			certFile, keyFile := pickCertForCipher(certs, cipher)
			// Per-subtest cert existence: GOST pairs are only generated when
			// gen.sh is run against a host that has gost-engine. Skip only the
			// affected subtest — non-GOST subtests are unaffected.
			if _, err := os.Stat(certFile); err != nil {
				t.Skipf("server cert for %s not found at %s: "+
					"run testdata/tarantool/certs/gen.sh with gost-engine", cipher, certFile)
			}
			if _, err := os.Stat(keyFile); err != nil {
				t.Skipf("server key for %s not found at %s: "+
					"run testdata/tarantool/certs/gen.sh with gost-engine", cipher, keyFile)
			}
			err = tarantoolConfigTmpl.Execute(cfg, struct {
				Port     int
				Cipher   string
				CertFile string
				KeyFile  string
				WorkDir  string
			}{
				Port:     port,
				Cipher:   cipher,
				CertFile: certFile,
				KeyFile:  keyFile,
				WorkDir:  workDir,
			})
			_ = cfg.Close()
			require.NoError(t, err, "render config")

			cmd, cancel := startTarantool(t, cfgPath, workDir)
			t.Cleanup(func() {
				cancel()
				_ = cmd.Wait()
			})

			addr := fmt.Sprintf("127.0.0.1:%d", port)
			require.NoErrorf(t, waitForTCP(addr, 30*time.Second),
				"tarantool-ee did not open %s", addr)

			dialer := tlsdialer.OpenSSLDialer{
				Address:    fmt.Sprintf("localhost:%d", port),
				User:       "test",
				Password:   "test",
				SslCaFile:  certs.CaFile,
				SslCiphers: cipher,
				Backend:    gostls.New(),
			}

			connectAndPing(t, dialer, fmt.Sprintf("%s on %s", cipher, addr))
		})
	}
}
